FROM node:18-alpine AS build

WORKDIR /app

COPY to-do-app/package.json to-do-app/package-lock.json ./
RUN npm install --production=false

COPY to-do-app/ .

RUN yarn build # Or npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]