# Generated by Django 5.1.7 on 2025-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Project_ID')),
                ('project_name', models.CharField(max_length=255, unique=True, verbose_name='Project_name')),
                ('project_description', models.TextField(blank=True, verbose_name='Project_description')),
            ],
        ),
    ]
