# Generated by Django 5.1.7 on 2025-03-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_endDate',
            field=models.DateField(blank=True, null=True, verbose_name='project_endDate'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_startDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='project_startDate'),
        ),
    ]
