# Generated by Django 5.1.5 on 2025-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_project_enddate_projects_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_startDate',
            field=models.DateField(blank=True, null=True, verbose_name='project_startDate'),
        ),
    ]
