# Generated by Django 5.1.7 on 2025-03-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Category',
            fields=[
                ('category_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category_ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='categoy_name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Task_ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Task_name')),
                ('description', models.TextField(verbose_name='Task_description')),
                ('label', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=12, verbose_name='Labels')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Task_start_date')),
                ('end_date', models.DateField(verbose_name='Task_end_date')),
                ('tasks_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_project', to='projects.projects')),
            ],
        ),
    ]
