# Generated by Django 5.1.7 on 2025-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In progress'), ('NOT_STARTED', 'Not started')], default='NOT_STARTED', max_length=12, verbose_name='Task_Status'),
        ),
    ]
