# Generated by Django 5.1.5 on 2025-03-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_category',
            old_name='category_Id',
            new_name='id',
        ),
    ]
