# Generated by Django 5.1.5 on 2025-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_category_id_task_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('In progress', 'IN PROGRESS'), ('Not started', 'NOT STARTED')], default='NOT STARTED', max_length=12, verbose_name='Task_Status'),
        ),
    ]
